#!/bin/sh
### BEGIN INIT INFO
# Provides:          hellopeter
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start hellopeter server at boot time
# Description:       Controls the hellopeter server
### END INIT INFO

APP_HOME=/usr/share/java
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=hellopeter
DESC="Simple Web Application Example" 
APP_USER=www-data
DAEMON="/usr/bin/java"
DAEMON_ARGS="-jar $APP_HOME/$NAME.jar"
LOGFILE="/var/log/hellopeter/webapp.log"

test -e $APP_HOME/$NAME.jar || exit 0

DEFAULT=/etc/default/$NAME

# Include defaults if available
if [ -f "$DEFAULT" ] ; then
	. "$DEFAULT"
fi
# Get configuration from /etc/hellopeter/server.conf
if [ -f /etc/${NAME}/server.conf ] ; then
  DAEMON_ARGS=" ${DAEMON_ARGS} "$(cat /etc/${NAME}/server.conf | tr '\n' ' ')
fi

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --chuid "$APP_USER" --chdir "$APP_HOME" --pidfile /var/run/$NAME.pid \
        --make-pidfile --exec $DAEMON -- $DAEMON_ARGS 2>&1 >> $LOGFILE & 
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid 2>&1 >> $LOGFILE || true
	echo "$NAME."
        rm -f /var/run/$NAME.pid
	;;
  restart)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid 2>&1 >> $LOGFILE || true
        rm -f /var/run/$NAME.pid
	sleep 1
        nohup start-stop-daemon --start --chuid "$APP_USER" --chdir "$APP_HOME" --pidfile /var/run/$NAME.pid \
                --make-pidfile --exec $DAEMON -- $DAEMON_ARGS 2>&1 >> $LOGFILE &
        echo "$NAME."
	;;
  status)
	status_of_proc -p /var/run/$NAME.pid "$DAEMON" $NAME && exit 0 || exit $?
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0

