#!/bin/bash
# postinst script for hellopeter
#
# see: dh_installdeb(1)
set -e
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
case "$1" in
    abort-upgrade)
     invoke-rc.d hellopeter stop 2>&1 > /dev/null
    ;;
    abort-remove)
     invoke-rc.d hellopeter stop 2>&1 > /dev/null 
    ;;
    configure|install)
     invoke-rc.d hellopeter start 2>&1 > /dev/null
     update-rc.d hellopeter defaults
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0

